/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

/**
 *
 * @author T&T Center
 */
public class QLDM extends javax.swing.JPanel {

    /**
     * Creates new form QLDM
     */
    public QLDM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMenuTab = new javax.swing.JTabbedPane();
        jpnTabNCC = new javax.swing.JPanel();
        jpnTabKhachHang = new javax.swing.JPanel();
        jpnMatHang = new javax.swing.JPanel();

        setLayout(new javax.swing.OverlayLayout(this));

        jtpMenuTab.setBackground(new java.awt.Color(26, 29, 31));
        jtpMenuTab.setForeground(new java.awt.Color(255, 255, 255));
        jtpMenuTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtpMenuTab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtpMenuTab.setName(""); // NOI18N
        jtpMenuTab.setOpaque(true);

        jpnTabNCC.setBackground(new java.awt.Color(255, 255, 255));
        jpnTabNCC.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnTabNCCLayout = new javax.swing.GroupLayout(jpnTabNCC);
        jpnTabNCC.setLayout(jpnTabNCCLayout);
        jpnTabNCCLayout.setHorizontalGroup(
            jpnTabNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        jpnTabNCCLayout.setVerticalGroup(
            jpnTabNCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jtpMenuTab.addTab("Nhà cung cấp", new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/parcel.png")), jpnTabNCC); // NOI18N

        javax.swing.GroupLayout jpnTabKhachHangLayout = new javax.swing.GroupLayout(jpnTabKhachHang);
        jpnTabKhachHang.setLayout(jpnTabKhachHangLayout);
        jpnTabKhachHangLayout.setHorizontalGroup(
            jpnTabKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        jpnTabKhachHangLayout.setVerticalGroup(
            jpnTabKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jtpMenuTab.addTab("Khách hàng", jpnTabKhachHang);

        javax.swing.GroupLayout jpnMatHangLayout = new javax.swing.GroupLayout(jpnMatHang);
        jpnMatHang.setLayout(jpnMatHangLayout);
        jpnMatHangLayout.setHorizontalGroup(
            jpnMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );
        jpnMatHangLayout.setVerticalGroup(
            jpnMatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jtpMenuTab.addTab("Mặt hàng", jpnMatHang);

        jtpMenuTab.setSelectedComponent(jpnTabNCC);

        add(jtpMenuTab);
        jtpMenuTab.getAccessibleContext().setAccessibleParent(jpnMatHang);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnMatHang;
    private javax.swing.JPanel jpnTabKhachHang;
    private javax.swing.JPanel jpnTabNCC;
    private javax.swing.JTabbedPane jtpMenuTab;
    // End of variables declaration//GEN-END:variables
}
