/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.DanhMuc;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author T&T Center
 */
public class QLDMView extends javax.swing.JPanel {

    /**
     * Creates new form QLDM
     */
    private ArrayList<DanhMuc> list = new ArrayList<>();
    public QLDMView() {
        initComponents();
        setView("NhaCungCap");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabNCC = new javax.swing.JPanel();
        titleNCC = new javax.swing.JLabel();
        tabKH = new javax.swing.JPanel();
        titleKH = new javax.swing.JLabel();
        tabMH = new javax.swing.JPanel();
        titleMH = new javax.swing.JLabel();
        viewContent = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(770, 444));

        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 80, 0));

        tabNCC.setBackground(new java.awt.Color(135, 143, 253));
        tabNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNCCMouseClicked(evt);
            }
        });
        tabNCC.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 14));

        titleNCC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titleNCC.setForeground(new java.awt.Color(255, 255, 255));
        titleNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/parcel.png"))); // NOI18N
        titleNCC.setText("Nhà cung cấp");
        titleNCC.setIconTextGap(10);
        titleNCC.setRequestFocusEnabled(false);
        tabNCC.add(titleNCC);

        jPanel1.add(tabNCC);

        tabKH.setBackground(new java.awt.Color(205, 163, 246));
        tabKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabKHMouseClicked(evt);
            }
        });
        tabKH.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 14));

        titleKH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titleKH.setForeground(new java.awt.Color(255, 255, 255));
        titleKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/customer (1).png"))); // NOI18N
        titleKH.setText("Khách hàng");
        titleKH.setIconTextGap(10);
        tabKH.add(titleKH);

        jPanel1.add(tabKH);

        tabMH.setBackground(new java.awt.Color(232, 208, 125));
        tabMH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMHMouseClicked(evt);
            }
        });
        tabMH.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 14));

        titleMH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titleMH.setForeground(new java.awt.Color(255, 255, 255));
        titleMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon/cubes (1).png"))); // NOI18N
        titleMH.setText("Mặt hàng");
        titleMH.setIconTextGap(10);
        tabMH.add(titleMH);

        jPanel1.add(tabMH);

        viewContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewContentLayout = new javax.swing.GroupLayout(viewContent);
        viewContent.setLayout(viewContentLayout);
        viewContentLayout.setHorizontalGroup(
            viewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viewContentLayout.setVerticalGroup(
            viewContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setView(String name) {
        viewContent.removeAll();
        viewContent.setLayout(new BorderLayout());
//        switch (name) {
//            case "NhaCungCap": node = new NhaCungCapView(); break;
//            case "KhachHang": node = new KhachHangView(); break;
//            case "MatHang": node = new MatHang(); break;
//            default: node = new NhaCungCapView();
//        }
        if (name.equalsIgnoreCase("NhaCungCap")) {
            NhaCungCapView nccView = new NhaCungCapView();
            viewContent.add(nccView);
            nccView.showListData();
        }
        if (name.equalsIgnoreCase("KhachHang")) {
//            KhachHangView khView = new KhachHang();
//            viewContent.add(khView);
        }
        
        viewContent.validate();
        viewContent.repaint();
    }
    
    private void tabNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNCCMouseClicked
        tabNCC.setBackground(new Color(135, 143, 253));
        tabKH.setBackground(new Color(205, 163, 246));
        tabMH.setBackground(new Color(232, 208, 125));
        setView("NhaCungCap");
        
    }//GEN-LAST:event_tabNCCMouseClicked

    private void tabKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabKHMouseClicked
        tabKH.setBackground(new Color(185, 128, 248));
        tabNCC.setBackground(new Color(169, 175, 251));
        tabMH.setBackground(new Color(232, 208, 125));
        setView("KhachHang");
    }//GEN-LAST:event_tabKHMouseClicked

    private void tabMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMHMouseClicked
        tabMH.setBackground(new Color(240, 198, 56));
        tabNCC.setBackground(new Color(169, 175, 251));
        tabKH.setBackground(new Color(205, 163, 246));
        setView("MatHang");
    }//GEN-LAST:event_tabMHMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel tabKH;
    private javax.swing.JPanel tabMH;
    private javax.swing.JPanel tabNCC;
    private javax.swing.JLabel titleKH;
    private javax.swing.JLabel titleMH;
    private javax.swing.JLabel titleNCC;
    private javax.swing.JPanel viewContent;
    // End of variables declaration//GEN-END:variables
}
